# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  #  apimatic_api client class.
  class Client
    include CoreLibrary
    attr_reader :config, :auth_managers

    # Access to apis_management controller.
    # @return [ApisManagementController] Returns the controller instance.
    def apis_management
      @apis_management ||= ApisManagementController.new @global_configuration
    end

    # Access to code_generation_imported_apis controller.
    # @return [CodeGenerationImportedApisController] Returns the controller instance.
    def code_generation_imported_apis
      @code_generation_imported_apis ||= CodeGenerationImportedApisController.new @global_configuration
    end

    # Access to code_generation_external_apis controller.
    # @return [CodeGenerationExternalApisController] Returns the controller instance.
    def code_generation_external_apis
      @code_generation_external_apis ||= CodeGenerationExternalApisController.new @global_configuration
    end

    # Access to transformation controller.
    # @return [TransformationController] Returns the controller instance.
    def transformation
      @transformation ||= TransformationController.new @global_configuration
    end

    # Access to docs_portal_management controller.
    # @return [DocsPortalManagementController] Returns the controller instance.
    def docs_portal_management
      @docs_portal_management ||= DocsPortalManagementController.new @global_configuration
    end

    # Access to api_validation_imported_apis controller.
    # @return [APIValidationImportedApisController] Returns the controller instance.
    def api_validation_imported_apis
      @api_validation_imported_apis ||= APIValidationImportedApisController.new @global_configuration
    end

    # Access to api_validation_external_apis controller.
    # @return [APIValidationExternalApisController] Returns the controller instance.
    def api_validation_external_apis
      @api_validation_external_apis ||= APIValidationExternalApisController.new @global_configuration
    end

    def initialize(
      connection: nil, adapter: :net_http_persistent, timeout: 60,
      max_retries: 0, retry_interval: 1, backoff_factor: 2,
      retry_statuses: [408, 413, 429, 500, 502, 503, 504, 521, 522, 524, 408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
      retry_methods: %i[get put get put], http_callback: nil,
      environment: Environment::PRODUCTION, authorization: nil,
      custom_header_authentication_credentials: nil, config: nil
    )
      @config = if config.nil?
                  Configuration.new(
                    connection: connection, adapter: adapter, timeout: timeout,
                    max_retries: max_retries, retry_interval: retry_interval,
                    backoff_factor: backoff_factor,
                    retry_statuses: retry_statuses,
                    retry_methods: retry_methods, http_callback: http_callback,
                    environment: environment, authorization: authorization,
                    custom_header_authentication_credentials: custom_header_authentication_credentials
                  )
                else
                  config
                end

      @global_configuration = GlobalConfiguration.new(client_configuration: @config)
                                                 .base_uri_executor(@config.method(:get_base_uri))
                                                 .global_errors(BaseController::GLOBAL_ERRORS)
                                                 .user_agent(BaseController.user_agent)

      initialize_auth_managers(@global_configuration)
      @global_configuration = @global_configuration.auth_managers(@auth_managers)
    end

    # Initializes the auth managers hash used for authenticating API calls.
    # @param [GlobalConfiguration] global_config The global configuration of the SDK)
    def initialize_auth_managers(global_config)
      @auth_managers = {}
      http_client_config = global_config.client_configuration
      %w[Authorization].each { |auth| @auth_managers[auth] = nil }
      @auth_managers['Authorization'] = CustomHeaderAuthentication.new(
        http_client_config.custom_header_authentication_credentials
      )
    end
  end
end
