# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # APIEntityIdentifier Model.
  class APIEntityIdentifier < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Unique API Entity Identifier
    # @return [String]
    attr_accessor :api_entity_id

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['api_entity_id'] = 'apiEntityId'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(api_entity_id = nil)
      @api_entity_id = api_entity_id
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      api_entity_id = hash.key?('apiEntityId') ? hash['apiEntityId'] : nil

      # Create object from extracted values.
      APIEntityIdentifier.new(api_entity_id)
    end
  end
end
