# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # APIMatic’s code generation engine has various code generation configurations
  # to customise the behaviour and outlook across the generated SDKS. This
  # structure encapsulates all settings for CodeGeneration.
  class CodeGenSettings < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Generate asynchronous code for API Calls and deserialization
    # @return [TrueClass | FalseClass]
    attr_accessor :is_async

    # Use HTTP Method prefixes for endpoint wrappers
    # @return [TrueClass | FalseClass]
    attr_accessor :use_http_method_prefix

    # Use "Model" postfixes for generated class names
    # @return [TrueClass | FalseClass]
    attr_accessor :use_model_prefix

    # Use "Enum" postfixes for enumerated types
    # @return [TrueClass | FalseClass]
    attr_accessor :use_enum_prefix

    # Use "Enum" postfixes for enumerated types
    # @return [TrueClass | FalseClass]
    attr_accessor :use_constructors_for_config

    # Use common SDK library to reduce code duplication
    # @return [TrueClass | FalseClass]
    attr_accessor :use_common_sdk_library

    # Generates interfaces for controller classes in the generated SDKs
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_interfaces

    # Generate Appveyor configuration file
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_appveyor_config

    # Generate CircleCI configuration file
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_circle_config

    # Generate Jenkins configuration file
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_jenkins_config

    # Generate Travis CI configuration file
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_travis_config

    # Use "AndroidManifest.xml" for config variables in Android
    # @return [TrueClass | FalseClass]
    attr_accessor :android_use_app_manifest

    # Use "App-Info.plist" file for config variables in iOS
    # @return [TrueClass | FalseClass]
    attr_accessor :ios_use_app_info_plist

    # Generate "CoreData" schema and entity classes in iOS?
    # @return [TrueClass | FalseClass]
    attr_accessor :ios_generate_core_data

    # Enable runscope
    # @return [TrueClass | FalseClass]
    attr_accessor :runscope_enabled

    # Collect Parameters as arrays
    # @return [TrueClass | FalseClass]
    attr_accessor :collapse_params_to_array

    # Attempts to preserve parameter order for endpoints
    # @return [TrueClass | FalseClass]
    attr_accessor :preserve_parameter_order

    # Append JSON/XML accept and content-type headers
    # @return [TrueClass | FalseClass]
    attr_accessor :append_content_headers

    # Append JSON/XML accept and content-type headers
    # @return [TrueClass | FalseClass]
    attr_accessor :model_serialization_is_json

    # Return a null value on HTTP 404
    # @return [TrueClass | FalseClass]
    attr_accessor :nullify404

    # Validate required parameters to be Not Null
    # @return [TrueClass | FalseClass]
    attr_accessor :validate_required_parameters

    # Allow models to have additional runtime properties
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_additional_model_properties

    # Allow models to have additional runtime properties
    # @return [TrueClass | FalseClass]
    attr_accessor :java_use_properties_config

    # Use "Controller" postfixes for generated controller classes
    # @return [TrueClass | FalseClass]
    attr_accessor :use_controller_prefix

    # Use Exception Prefixes
    # @return [TrueClass | FalseClass]
    attr_accessor :use_exception_prefix

    # Parameter Array format with index or without
    # @return [String]
    attr_accessor :parameter_array_format

    # Configure the HTTP client for Objective C
    # @return [String]
    attr_accessor :obj_c_http_client

    # Configure the HTTP client for C#
    # @return [String]
    attr_accessor :c_sharp_http_client

    # Configure the HTTP client for  Android
    # @return [String]
    attr_accessor :android_http_client

    # Configure the HTTP client for node
    # @return [String]
    attr_accessor :node_http_client

    # Configure the HTTP client for PHP
    # @return [String]
    attr_accessor :php_http_client

    # Configure the HTTP client for PHP
    # @return [Integer]
    attr_accessor :body_serialization

    # Specify type of array serialisation
    # @return [String]
    attr_accessor :array_serialization

    # This option specifies the duration (in seconds) after which requests would
    # timeout
    # @return [Integer]
    attr_accessor :timeout

    # Enabling this generates code in the SDKs for logging events in the API
    # cycle using a library.
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_logging

    # Enabling caching of responses (not available in all languages)
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_http_cache

    # Specify number of retries
    # @return [Integer]
    attr_accessor :retries

    # Specify retry interval in case of failures
    # @return [Integer]
    attr_accessor :retry_interval

    # Generate advanced read me files
    # @return [TrueClass | FalseClass]
    attr_accessor :generate_advanced_docs

    # Store Timezone information for the generation
    # @return [TrueClass | FalseClass]
    attr_accessor :store_timezone_information

    # Use "Controller" postfixes for generated controller classes
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_php_composer_version_string

    # Specify Security Protocols
    # @return [Array[String]]
    attr_accessor :security_protocols

    # Use underscores before and after numbers for underscore case
    # @return [TrueClass | FalseClass]
    attr_accessor :underscore_numbers

    # Allow usage of a Singleton Pattern
    # @return [TrueClass | FalseClass]
    attr_accessor :use_singleton_pattern

    # Files/dependencies used for linting are not generated if this option is
    # enabled
    # @return [TrueClass | FalseClass]
    attr_accessor :disable_linting

    # Create a configuration option in SDKs to optionally skip certificate
    # verification when establishing HTTPS connections.
    # @return [TrueClass | FalseClass]
    attr_accessor :allow_skipping_ssl_cert_verification

    # Apply Customisations
    # @return [Array[String]]
    attr_accessor :apply_customizations

    # Enabling this will stop splitting of words when converting identifiers
    # from API specification to language-specific identifiers.
    # @return [Array[String]]
    attr_accessor :do_not_split_words

    # Sorts resources such as endpoints, endpoint groups and models in generated
    # documentation
    # @return [TrueClass | FalseClass]
    attr_accessor :sort_resources

    # Enable a global user agent
    # @return [TrueClass | FalseClass]
    attr_accessor :enable_global_user_agent

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['is_async'] = 'isAsync'
      @_hash['use_http_method_prefix'] = 'useHttpMethodPrefix'
      @_hash['use_model_prefix'] = 'useModelPrefix'
      @_hash['use_enum_prefix'] = 'useEnumPrefix'
      @_hash['use_constructors_for_config'] = 'useConstructorsForConfig'
      @_hash['use_common_sdk_library'] = 'useCommonSdkLibrary'
      @_hash['generate_interfaces'] = 'generateInterfaces'
      @_hash['generate_appveyor_config'] = 'generateAppveyorConfig'
      @_hash['generate_circle_config'] = 'generateCircleConfig'
      @_hash['generate_jenkins_config'] = 'generateJenkinsConfig'
      @_hash['generate_travis_config'] = 'generateTravisConfig'
      @_hash['android_use_app_manifest'] = 'androidUseAppManifest'
      @_hash['ios_use_app_info_plist'] = 'iosUseAppInfoPlist'
      @_hash['ios_generate_core_data'] = 'iosGenerateCoreData'
      @_hash['runscope_enabled'] = 'runscopeEnabled'
      @_hash['collapse_params_to_array'] = 'collapseParamsToArray'
      @_hash['preserve_parameter_order'] = 'preserveParameterOrder'
      @_hash['append_content_headers'] = 'appendContentHeaders'
      @_hash['model_serialization_is_json'] = 'modelSerializationIsJSON'
      @_hash['nullify404'] = 'nullify404'
      @_hash['validate_required_parameters'] = 'validateRequiredParameters'
      @_hash['enable_additional_model_properties'] =
        'enableAdditionalModelProperties'
      @_hash['java_use_properties_config'] = 'javaUsePropertiesConfig'
      @_hash['use_controller_prefix'] = 'useControllerPrefix'
      @_hash['use_exception_prefix'] = 'useExceptionPrefix'
      @_hash['parameter_array_format'] = 'parameterArrayFormat'
      @_hash['obj_c_http_client'] = 'objCHttpClient'
      @_hash['c_sharp_http_client'] = 'cSharpHttpClient'
      @_hash['android_http_client'] = 'androidHttpClient'
      @_hash['node_http_client'] = 'nodeHttpClient'
      @_hash['php_http_client'] = 'phpHttpClient'
      @_hash['body_serialization'] = 'bodySerialization'
      @_hash['array_serialization'] = 'arraySerialization'
      @_hash['timeout'] = 'timeout'
      @_hash['enable_logging'] = 'enableLogging'
      @_hash['enable_http_cache'] = 'enableHttpCache'
      @_hash['retries'] = 'retries'
      @_hash['retry_interval'] = 'retryInterval'
      @_hash['generate_advanced_docs'] = 'generateAdvancedDocs'
      @_hash['store_timezone_information'] = 'storeTimezoneInformation'
      @_hash['enable_php_composer_version_string'] =
        'enablePhpComposerVersionString'
      @_hash['security_protocols'] = 'securityProtocols'
      @_hash['underscore_numbers'] = 'underscoreNumbers'
      @_hash['use_singleton_pattern'] = 'useSingletonPattern'
      @_hash['disable_linting'] = 'disableLinting'
      @_hash['allow_skipping_ssl_cert_verification'] =
        'allowSkippingSSLCertVerification'
      @_hash['apply_customizations'] = 'applyCustomizations'
      @_hash['do_not_split_words'] = 'doNotSplitWords'
      @_hash['sort_resources'] = 'sortResources'
      @_hash['enable_global_user_agent'] = 'enableGlobalUserAgent'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(is_async = nil,
                   use_http_method_prefix = nil,
                   use_model_prefix = nil,
                   use_enum_prefix = nil,
                   use_constructors_for_config = nil,
                   use_common_sdk_library = nil,
                   generate_interfaces = nil,
                   generate_appveyor_config = nil,
                   generate_circle_config = nil,
                   generate_jenkins_config = nil,
                   generate_travis_config = nil,
                   android_use_app_manifest = nil,
                   ios_use_app_info_plist = nil,
                   ios_generate_core_data = nil,
                   runscope_enabled = nil,
                   collapse_params_to_array = nil,
                   preserve_parameter_order = nil,
                   append_content_headers = nil,
                   model_serialization_is_json = nil,
                   nullify404 = nil,
                   validate_required_parameters = nil,
                   enable_additional_model_properties = nil,
                   java_use_properties_config = nil,
                   use_controller_prefix = nil,
                   use_exception_prefix = nil,
                   parameter_array_format = nil,
                   obj_c_http_client = nil,
                   c_sharp_http_client = nil,
                   android_http_client = nil,
                   node_http_client = nil,
                   php_http_client = nil,
                   body_serialization = nil,
                   array_serialization = nil,
                   timeout = nil,
                   enable_logging = nil,
                   enable_http_cache = nil,
                   retries = nil,
                   retry_interval = nil,
                   generate_advanced_docs = nil,
                   store_timezone_information = nil,
                   enable_php_composer_version_string = nil,
                   security_protocols = nil,
                   underscore_numbers = nil,
                   use_singleton_pattern = nil,
                   disable_linting = nil,
                   allow_skipping_ssl_cert_verification = nil,
                   apply_customizations = nil,
                   do_not_split_words = nil,
                   sort_resources = nil,
                   enable_global_user_agent = nil)
      @is_async = is_async
      @use_http_method_prefix = use_http_method_prefix
      @use_model_prefix = use_model_prefix
      @use_enum_prefix = use_enum_prefix
      @use_constructors_for_config = use_constructors_for_config
      @use_common_sdk_library = use_common_sdk_library
      @generate_interfaces = generate_interfaces
      @generate_appveyor_config = generate_appveyor_config
      @generate_circle_config = generate_circle_config
      @generate_jenkins_config = generate_jenkins_config
      @generate_travis_config = generate_travis_config
      @android_use_app_manifest = android_use_app_manifest
      @ios_use_app_info_plist = ios_use_app_info_plist
      @ios_generate_core_data = ios_generate_core_data
      @runscope_enabled = runscope_enabled
      @collapse_params_to_array = collapse_params_to_array
      @preserve_parameter_order = preserve_parameter_order
      @append_content_headers = append_content_headers
      @model_serialization_is_json = model_serialization_is_json
      @nullify404 = nullify404
      @validate_required_parameters = validate_required_parameters
      @enable_additional_model_properties = enable_additional_model_properties
      @java_use_properties_config = java_use_properties_config
      @use_controller_prefix = use_controller_prefix
      @use_exception_prefix = use_exception_prefix
      @parameter_array_format = parameter_array_format
      @obj_c_http_client = obj_c_http_client
      @c_sharp_http_client = c_sharp_http_client
      @android_http_client = android_http_client
      @node_http_client = node_http_client
      @php_http_client = php_http_client
      @body_serialization = body_serialization
      @array_serialization = array_serialization
      @timeout = timeout
      @enable_logging = enable_logging
      @enable_http_cache = enable_http_cache
      @retries = retries
      @retry_interval = retry_interval
      @generate_advanced_docs = generate_advanced_docs
      @store_timezone_information = store_timezone_information
      @enable_php_composer_version_string = enable_php_composer_version_string
      @security_protocols = security_protocols
      @underscore_numbers = underscore_numbers
      @use_singleton_pattern = use_singleton_pattern
      @disable_linting = disable_linting
      @allow_skipping_ssl_cert_verification = allow_skipping_ssl_cert_verification
      @apply_customizations = apply_customizations
      @do_not_split_words = do_not_split_words
      @sort_resources = sort_resources
      @enable_global_user_agent = enable_global_user_agent
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      is_async = hash.key?('isAsync') ? hash['isAsync'] : nil
      use_http_method_prefix =
        hash.key?('useHttpMethodPrefix') ? hash['useHttpMethodPrefix'] : nil
      use_model_prefix =
        hash.key?('useModelPrefix') ? hash['useModelPrefix'] : nil
      use_enum_prefix = hash.key?('useEnumPrefix') ? hash['useEnumPrefix'] : nil
      use_constructors_for_config =
        hash.key?('useConstructorsForConfig') ? hash['useConstructorsForConfig'] : nil
      use_common_sdk_library =
        hash.key?('useCommonSdkLibrary') ? hash['useCommonSdkLibrary'] : nil
      generate_interfaces =
        hash.key?('generateInterfaces') ? hash['generateInterfaces'] : nil
      generate_appveyor_config =
        hash.key?('generateAppveyorConfig') ? hash['generateAppveyorConfig'] : nil
      generate_circle_config =
        hash.key?('generateCircleConfig') ? hash['generateCircleConfig'] : nil
      generate_jenkins_config =
        hash.key?('generateJenkinsConfig') ? hash['generateJenkinsConfig'] : nil
      generate_travis_config =
        hash.key?('generateTravisConfig') ? hash['generateTravisConfig'] : nil
      android_use_app_manifest =
        hash.key?('androidUseAppManifest') ? hash['androidUseAppManifest'] : nil
      ios_use_app_info_plist =
        hash.key?('iosUseAppInfoPlist') ? hash['iosUseAppInfoPlist'] : nil
      ios_generate_core_data =
        hash.key?('iosGenerateCoreData') ? hash['iosGenerateCoreData'] : nil
      runscope_enabled =
        hash.key?('runscopeEnabled') ? hash['runscopeEnabled'] : nil
      collapse_params_to_array =
        hash.key?('collapseParamsToArray') ? hash['collapseParamsToArray'] : nil
      preserve_parameter_order =
        hash.key?('preserveParameterOrder') ? hash['preserveParameterOrder'] : nil
      append_content_headers =
        hash.key?('appendContentHeaders') ? hash['appendContentHeaders'] : nil
      model_serialization_is_json =
        hash.key?('modelSerializationIsJSON') ? hash['modelSerializationIsJSON'] : nil
      nullify404 = hash.key?('nullify404') ? hash['nullify404'] : nil
      validate_required_parameters =
        hash.key?('validateRequiredParameters') ? hash['validateRequiredParameters'] : nil
      enable_additional_model_properties =
        hash.key?('enableAdditionalModelProperties') ? hash['enableAdditionalModelProperties'] : nil
      java_use_properties_config =
        hash.key?('javaUsePropertiesConfig') ? hash['javaUsePropertiesConfig'] : nil
      use_controller_prefix =
        hash.key?('useControllerPrefix') ? hash['useControllerPrefix'] : nil
      use_exception_prefix =
        hash.key?('useExceptionPrefix') ? hash['useExceptionPrefix'] : nil
      parameter_array_format =
        hash.key?('parameterArrayFormat') ? hash['parameterArrayFormat'] : nil
      obj_c_http_client =
        hash.key?('objCHttpClient') ? hash['objCHttpClient'] : nil
      c_sharp_http_client =
        hash.key?('cSharpHttpClient') ? hash['cSharpHttpClient'] : nil
      android_http_client =
        hash.key?('androidHttpClient') ? hash['androidHttpClient'] : nil
      node_http_client =
        hash.key?('nodeHttpClient') ? hash['nodeHttpClient'] : nil
      php_http_client = hash.key?('phpHttpClient') ? hash['phpHttpClient'] : nil
      body_serialization =
        hash.key?('bodySerialization') ? hash['bodySerialization'] : nil
      array_serialization =
        hash.key?('arraySerialization') ? hash['arraySerialization'] : nil
      timeout = hash.key?('timeout') ? hash['timeout'] : nil
      enable_logging = hash.key?('enableLogging') ? hash['enableLogging'] : nil
      enable_http_cache =
        hash.key?('enableHttpCache') ? hash['enableHttpCache'] : nil
      retries = hash.key?('retries') ? hash['retries'] : nil
      retry_interval = hash.key?('retryInterval') ? hash['retryInterval'] : nil
      generate_advanced_docs =
        hash.key?('generateAdvancedDocs') ? hash['generateAdvancedDocs'] : nil
      store_timezone_information =
        hash.key?('storeTimezoneInformation') ? hash['storeTimezoneInformation'] : nil
      enable_php_composer_version_string =
        hash.key?('enablePhpComposerVersionString') ? hash['enablePhpComposerVersionString'] : nil
      security_protocols =
        hash.key?('securityProtocols') ? hash['securityProtocols'] : nil
      underscore_numbers =
        hash.key?('underscoreNumbers') ? hash['underscoreNumbers'] : nil
      use_singleton_pattern =
        hash.key?('useSingletonPattern') ? hash['useSingletonPattern'] : nil
      disable_linting =
        hash.key?('disableLinting') ? hash['disableLinting'] : nil
      allow_skipping_ssl_cert_verification =
        hash.key?('allowSkippingSSLCertVerification') ? hash['allowSkippingSSLCertVerification'] : nil
      apply_customizations =
        hash.key?('applyCustomizations') ? hash['applyCustomizations'] : nil
      do_not_split_words =
        hash.key?('doNotSplitWords') ? hash['doNotSplitWords'] : nil
      sort_resources = hash.key?('sortResources') ? hash['sortResources'] : nil
      enable_global_user_agent =
        hash.key?('enableGlobalUserAgent') ? hash['enableGlobalUserAgent'] : nil

      # Create object from extracted values.
      CodeGenSettings.new(is_async,
                          use_http_method_prefix,
                          use_model_prefix,
                          use_enum_prefix,
                          use_constructors_for_config,
                          use_common_sdk_library,
                          generate_interfaces,
                          generate_appveyor_config,
                          generate_circle_config,
                          generate_jenkins_config,
                          generate_travis_config,
                          android_use_app_manifest,
                          ios_use_app_info_plist,
                          ios_generate_core_data,
                          runscope_enabled,
                          collapse_params_to_array,
                          preserve_parameter_order,
                          append_content_headers,
                          model_serialization_is_json,
                          nullify404,
                          validate_required_parameters,
                          enable_additional_model_properties,
                          java_use_properties_config,
                          use_controller_prefix,
                          use_exception_prefix,
                          parameter_array_format,
                          obj_c_http_client,
                          c_sharp_http_client,
                          android_http_client,
                          node_http_client,
                          php_http_client,
                          body_serialization,
                          array_serialization,
                          timeout,
                          enable_logging,
                          enable_http_cache,
                          retries,
                          retry_interval,
                          generate_advanced_docs,
                          store_timezone_information,
                          enable_php_composer_version_string,
                          security_protocols,
                          underscore_numbers,
                          use_singleton_pattern,
                          disable_linting,
                          allow_skipping_ssl_cert_verification,
                          apply_customizations,
                          do_not_split_words,
                          sort_resources,
                          enable_global_user_agent)
    end
  end
end
