# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # The structure contains API specification formats that Transformer can
  # convert to.
  class ExportFormats
    EXPORT_FORMATS = [
      # TODO: Write general description for APIMATIC
      APIMATIC = 'APIMATIC'.freeze,

      # TODO: Write general description for WADL2009
      WADL2009 = 'WADL2009'.freeze,

      # TODO: Write general description for WSDL
      WSDL = 'WSDL'.freeze,

      # TODO: Write general description for SWAGGER10
      SWAGGER10 = 'Swagger10'.freeze,

      # TODO: Write general description for SWAGGER20
      SWAGGER20 = 'Swagger20'.freeze,

      # TODO: Write general description for SWAGGERYAML
      SWAGGERYAML = 'SwaggerYaml'.freeze,

      # OpenAPI v3.0 (JSON)
      OAS3 = 'OpenApi3Json'.freeze,

      # TODO: Write general description for OPENAPI3YAML
      OPENAPI3YAML = 'OpenApi3Yaml'.freeze,

      # TODO: Write general description for APIBLUEPRINT
      APIBLUEPRINT = 'APIBluePrint'.freeze,

      # TODO: Write general description for RAML
      RAML = 'RAML'.freeze,

      # TODO: Write general description for RAML10
      RAML10 = 'RAML10'.freeze,

      # TODO: Write general description for POSTMAN10
      POSTMAN10 = 'Postman10'.freeze,

      # TODO: Write general description for POSTMAN20
      POSTMAN20 = 'Postman20'.freeze,

      # TODO: Write general description for GRAPHQLSCHEMA
      GRAPHQLSCHEMA = 'GraphQlSchema'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      EXPORT_FORMATS.include?(value)
    end
  end
end
