# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # MetaData Model.
  class MetaData < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # TODO: Write general description for this method
    # @return [ImportValidationSummary]
    attr_accessor :import_validation_summary

    # TODO: Write general description for this method
    # @return [ApiValidationSummary]
    attr_accessor :api_validation_summary

    # TODO: Write general description for this method
    # @return [DocsValidationSummary]
    attr_accessor :docs_validation_summary

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['import_validation_summary'] = 'importValidationSummary'
      @_hash['api_validation_summary'] = 'apiValidationSummary'
      @_hash['docs_validation_summary'] = 'docsValidationSummary'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(import_validation_summary = nil,
                   api_validation_summary = nil,
                   docs_validation_summary = nil)
      @import_validation_summary = import_validation_summary
      @api_validation_summary = api_validation_summary
      @docs_validation_summary = docs_validation_summary
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      if hash['importValidationSummary']
        import_validation_summary = ImportValidationSummary.from_hash(hash['importValidationSummary'])
      end
      api_validation_summary = ApiValidationSummary.from_hash(hash['apiValidationSummary']) if
        hash['apiValidationSummary']
      docs_validation_summary = DocsValidationSummary.from_hash(hash['docsValidationSummary']) if
        hash['docsValidationSummary']

      # Create object from extracted values.
      MetaData.new(import_validation_summary,
                   api_validation_summary,
                   docs_validation_summary)
    end
  end
end
