# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # ParamterFormatDetails Model.
  class ParamterFormatDetails < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # Specify Parameter Format
    # @return [String]
    attr_accessor :param_format

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['param_format'] = 'ParamFormat'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(param_format = nil)
      @param_format = param_format
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      param_format = hash.key?('ParamFormat') ? hash['ParamFormat'] : nil

      # Create object from extracted values.
      ParamterFormatDetails.new(param_format)
    end
  end
end
