# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # PlatformsTemplate Model.
  class PlatformsTemplate < BaseModel
    SKIP = Object.new
    private_constant :SKIP

    # The structure contains platforms that APIMatic CodeGen can generate SDKs
    # and Docs in.
    # @return [Platforms]
    attr_accessor :template

    # A mapping from model property names to API property names.
    def self.names
      @_hash = {} if @_hash.nil?
      @_hash['template'] = 'template'
      @_hash
    end

    # An array for optional fields
    def self.optionals
      []
    end

    # An array for nullable fields
    def self.nullables
      []
    end

    def initialize(template = Platforms::CS_NET_STANDARD_LIB)
      @template = template
    end

    # Creates an instance of the object from a hash.
    def self.from_hash(hash)
      return nil unless hash

      # Extract variables from the hash.
      template = hash['template'] ||= Platforms::CS_NET_STANDARD_LIB

      # Create object from extracted values.
      PlatformsTemplate.new(template)
    end
  end
end
