# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

module ApimaticApi
  # The structure contains platforms that APIMatic CodeGen can generate SDKs and
  # Docs in.
  class Platforms
    PLATFORMS = [
      # .NET Standard Library
      CS_NET_STANDARD_LIB = 'CS_NET_STANDARD_LIB'.freeze,

      # JAVA
      JAVA_ECLIPSE_JRE_LIB = 'JAVA_ECLIPSE_JRE_LIB'.freeze,

      # PHP
      PHP_GENERIC_LIB_V2 = 'PHP_GENERIC_LIB'.freeze,

      # Python
      PYTHON_GENERIC_LIB = 'PYTHON_GENERIC_LIB'.freeze,

      # Ruby
      RUBY_GENERIC_LIB = 'RUBY_GENERIC_LIB'.freeze,

      # Typescript
      TS_GENERIC_LIB = 'TS_GENERIC_LIB'.freeze,

      # Go
      GO_GENERIC_LIB = 'GO_GENERIC_LIB'.freeze
    ].freeze

    def self.validate(value)
      return false if value.nil?

      PLATFORMS.include?(value)
    end
  end
end
