# apimatic_api
#
# This file was automatically generated by APIMATIC v2.0
# ( https://apimatic.io ).

require_relative 'controller_test_base'

class APIValidationExternalApisControllerTests < ControllerTestBase
  # Called only once for the class before any test has executed
  def setup
    setup_class
    @controller = @client.api_validation_external_apis
    @response_catcher = @controller.http_call_back
  end

  # Validate an API by providing the URL of the API specification file.
  #
  #You can also specify [API Metadata](https://docs.apimatic.io/manage-apis/apimatic-metadata) while validating the API using this endpoint. When specifying Metadata, the URL provided will be that of a zip file containing the API specification file and the `APIMATIC-META` json file.
  def test_validate_api_via_url
    # Parameters for the API call
    description_url = 'https://petstore.swagger.io/v2/swagger.json'

    # Perform the API call through the SDK function
    result = @controller.validate_api_via_url(description_url)

    # Test response code
    assert_equal(200, @response_catcher.response.status_code)

    # Test headers
    expected_headers = {}
    expected_headers['content-type'] = 'application/json'

    assert(ComparisonHelper.match_headers(expected_headers, @response_catcher.response.headers))

    # Test whether the captured response is as we expected
    refute_nil(result)
    expected_body = JSON.parse(
      '{"success":true,"errors":[],"warnings":["Media type <i><code>applicatio'\
      'n/json; charset=utf-8</code></i> content definition of response code <i'\
      '><code>429</code></i> in endpoint <i><code>getRealTimeData</code></i> o'\
      'f group <i><code>data</code></i> contains an example value with followi'\
      'ng undeclared fields: <i><code>detail</i></code>.","Endpoint <i><code>g'\
      'etRealTimeData</code></i> has an example specified for error code <i><c'\
      'ode>429</code></i> which contains following undeclared fields: <i><code'\
      '>detail</i></code>.","Media type <i><code>application/json; charset=utf'\
      '-8</code></i> content definition of response code <i><code>429</code></'\
      'i> in endpoint <i><code>getDataPerCategory</code></i> of group <i><code'\
      '>data</code></i> contains an example value with following undeclared fi'\
      'elds: <i><code>detail</i></code>.","Endpoint <i><code>getDataPerCategor'\
      'y</code></i> has an example specified for error code <i><code>429</code'\
      '></i> which contains following undeclared fields: <i><code>detail</i></'\
      'code>.","Media type <i><code>application/json; charset=utf-8</code></i>'\
      ' content definition of response code <i><code>429</code></i> in endpoin'\
      't <i><code>getData</code></i> of group <i><code>data</code></i> contain'\
      's an example value with following undeclared fields: <i><code>detail</i'\
      '></code>.","Endpoint <i><code>getData</code></i> has an example specifi'\
      'ed for error code <i><code>429</code></i> which contains following unde'\
      'clared fields: <i><code>detail</i></code>.","Media type <i><code>applic'\
      'ation/json; charset=utf-8</code></i> content definition of response cod'\
      'e <i><code>429</code></i> in endpoint <i><code>getActiveStatuses</code>'\
      '</i> of group <i><code>statuses</code></i> contains an example value wi'\
      'th following undeclared fields: <i><code>detail</i></code>.","Endpoint '\
      '<i><code>getActiveStatuses</code></i> has an example specified for erro'\
      'r code <i><code>429</code></i> which contains following undeclared fiel'\
      'ds: <i><code>detail</i></code>.","Media type <i><code>application/json;'\
      ' charset=utf-8</code></i> content definition of response code <i><code>'\
      '200</code></i> in endpoint <i><code>getDevices</code></i> of group <i><'\
      'code>assets</code></i> contains an example value with following undecla'\
      'red fields: <i><code>deviceModelId</code></i>, <i><code>manufacturer</c'\
      'ode></i>, <i><code>model</i></code>.","Media type <i><code>application/'\
      'json; charset=utf-8</code></i> content definition of response code <i><'\
      'code>429</code></i> in endpoint <i><code>getDevices</code></i> of group'\
      ' <i><code>assets</code></i> contains an example value with following un'\
      'declared fields: <i><code>detail</i></code>.","Endpoint <i><code>getDev'\
      'ices</code></i> has an example specified for error code <i><code>429</c'\
      'ode></i> which contains following undeclared fields: <i><code>detail</i'\
      '></code>.","Media type <i><code>application/json; charset=utf-8</code><'\
      '/i> content definition of response code <i><code>429</code></i> in endp'\
      'oint <i><code>getAlarms</code></i> of group <i><code>alerts</code></i> '\
      'contains an example value with following undeclared fields: <i><code>de'\
      'tail</i></code>.","Endpoint <i><code>getAlarms</code></i> has an exampl'\
      'e specified for error code <i><code>429</code></i> which contains follo'\
      'wing undeclared fields: <i><code>detail</i></code>.","Media type <i><co'\
      'de>application/json; charset=utf-8</code></i> content definition of res'\
      'ponse code <i><code>429</code></i> in endpoint <i><code>getActiveAlerts'\
      '</code></i> of group <i><code>alerts</code></i> contains an example val'\
      'ue with following undeclared fields: <i><code>detail</i></code>.","Endp'\
      'oint <i><code>getActiveAlerts</code></i> has an example specified for e'\
      'rror code <i><code>429</code></i> which contains following undeclared f'\
      'ields: <i><code>detail</i></code>.","Media type <i><code>application/js'\
      'on; charset=utf-8</code></i> content definition of response code <i><co'\
      'de>429</code></i> in endpoint <i><code>getAlerts</code></i> of group <i'\
      '><code>alerts</code></i> contains an example value with following undec'\
      'lared fields: <i><code>detail</i></code>.","Endpoint <i><code>getAlerts'\
      '</code></i> has an example specified for error code <i><code>429</code>'\
      '</i> which contains following undeclared fields: <i><code>detail</i></c'\
      'ode>.","Media type <i><code>application/json; charset=utf-8</code></i> '\
      'content definition of response code <i><code>429</code></i> in endpoint'\
      ' <i><code>getConfiguration</code></i> of group <i><code>configuration d'\
      'ata</code></i> contains an example value with following undeclared fiel'\
      'ds: <i><code>detail</i></code>.","Endpoint <i><code>getConfiguration</c'\
      'ode></i> has an example specified for error code <i><code>429</code></i'\
      '> which contains following undeclared fields: <i><code>detail</i></code'\
      '>.","Media type <i><code>application/json; charset=utf-8</code></i> con'\
      'tent definition of response code <i><code>429</code></i> in endpoint <i'\
      '><code>getActiveAlarms</code></i> of group <i><code>alerts</code></i> c'\
      'ontains an example value with following undeclared fields: <i><code>det'\
      'ail</i></code>.","Endpoint <i><code>getActiveAlarms</code></i> has an e'\
      'xample specified for error code <i><code>429</code></i> which contains '\
      'following undeclared fields: <i><code>detail</i></code>.","Media type <'\
      'i><code>application/json; charset=utf-8</code></i> content definition o'\
      'f response code <i><code>429</code></i> in endpoint <i><code>getPowerCu'\
      'rves</code></i> of group <i><code>assets</code></i> contains an example'\
      ' value with following undeclared fields: <i><code>detail</i></code>.","'\
      'Endpoint <i><code>getPowerCurves</code></i> has an example specified fo'\
      'r error code <i><code>429</code></i> which contains following undeclare'\
      'd fields: <i><code>detail</i></code>.","Media type <i><code>application'\
      '/json; charset=utf-8</code></i> content definition of response code <i>'\
      '<code>429</code></i> in endpoint <i><code>getDataSignals</code></i> of '\
      'group <i><code>data</code></i> contains an example value with following'\
      ' undeclared fields: <i><code>detail</i></code>.","Endpoint <i><code>get'\
      'DataSignals</code></i> has an example specified for error code <i><code'\
      '>429</code></i> which contains following undeclared fields: <i><code>de'\
      'tail</i></code>.","Media type <i><code>application/json; charset=utf-8<'\
      '/code></i> content definition of response code <i><code>429</code></i> '\
      'in endpoint <i><code>getStatuses</code></i> of group <i><code>statuses<'\
      '/code></i> contains an example value with following undeclared fields: '\
      '<i><code>detail</i></code>.","Endpoint <i><code>getStatuses</code></i> '\
      'has an example specified for error code <i><code>429</code></i> which c'\
      'ontains following undeclared fields: <i><code>detail</i></code>.","Medi'\
      'a type <i><code>application/json; charset=utf-8</code></i> content defi'\
      'nition of response code <i><code>429</code></i> in endpoint <i><code>ge'\
      'tSites</code></i> of group <i><code>assets</code></i> contains an examp'\
      'le value with following undeclared fields: <i><code>detail</i></code>."'\
      ',"Endpoint <i><code>getSites</code></i> has an example specified for er'\
      'ror code <i><code>429</code></i> which contains following undeclared fi'\
      'elds: <i><code>detail</i></code>."],"messages":["One or more elements i'\
      'n the API specification has a missing description field."]}'
    )
    received_body = JSON.parse(@response_catcher.response.raw_body)
    assert(ComparisonHelper.match_body(expected_body, received_body))
  end

end